### ISSUE TITLE
Creating Feature Collection Object from REST API

### ISSUE THREAD

**Issue by rachmatg** [chuyentt/geojson_vi#2]
Hi Chutentt,

I need to make a GeoJSON object from REST api, so I modify your geojson_vi.dart and add this:
export 'src/classes/feature_collection.dart';

And just use this:
var features = new GeoJSONFeatureCollection.fromMap(geo);

Where geo is geojson object returned from REST api.

It works well, so may be you want to update in the next release.

Thank you.

**Comment by chuyentt** [comment]
Thank you,
I've just released the new version 1.2.3. Please update the package and run a gain.

**Comment by chuyentt** [comment]
> Hi Chutentt,
> 
> I need to make a GeoJSON object from REST api, so I modify your geojson_vi.dart and add this:
> export 'src/classes/feature_collection.dart';
> 
> And just use this:
> var features = new GeoJSONFeatureCollection.fromMap(geo);
> 
> Where geo is geojson object returned from REST api.
> 
> It works well, so may be you want to update in the next release.
> 
> Thank you.

Thank you,
I've just released the new version 1.2.3. Please update the package and run a gain.
