### ISSUE TITLE
How to handle if the json is too large? 

### ISSUE THREAD

**Issue by ankittiwari25** [chuyentt/geojson_vi#21]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chuyentt** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context** Add any other context or screenshots about the feature request here.

Hi @ankittiwari25 ,

Thank you for bringing up this issue. We appreciate your input and the time you took to report it.

As there hasn't been any further activity or additional input on this issue for a while, we are closing it for now. If you still have questions or if this is still a problem, please feel free to reopen the issue or create a new one with updated details.

Thank you for your understanding and continued support.

Best regards,
Chuyen
