### ISSUE TITLE
Create a set() for the feature's properties

### ISSUE THREAD

**Issue by steinmetz** [chuyentt/geojson_vi#3]
What do you think if there would be a setter for the properties or make the attribute public?

While I create a new feature, sometimes I already have a map of the properties or it would be easier to set them like this:

```dart
  final geom_point = GeoJSONPoint(pos);
  final feature_point = GeoJSONFeature(geom_point);
  feature_point.properties = {
      'key1': 'value1',
      'key2': 'value2',
      'key3': 'value3',
      ...
  }
```

What do you think?

**Comment by steinmetz** [comment]
I think I can use addAll for that...

```dart
feature.properties.addAll(
      {...} 
    );
```

**Comment by chuyentt** [comment]
> What do you think if there would be a setter for the properties or make the attribute public?
> 
> While I create a new feature, sometimes I already have a map of the properties or it would be easier to set them like this:
> 
> ```dart
>   final geom_point = GeoJSONPoint(pos);
>   final feature_point = GeoJSONFeature(geom_point);
>   feature_point.properties = {
>       'key1': 'value1',
>       'key2': 'value2',
>       'key3': 'value3',
>       ...
>   }
> ```
> 
> What do you think?

I think that's better, thank you! Please update package to geojson_vi: ^1.3.1+3 for this
