### ISSUE TITLE
rendering?

### ISSUE THREAD

**Issue by JoeMurray** [chuyentt/geojson_vi#5]
Do you have a recommendation for an open source package for rendering geoJson in flutter web? We don't want openstreetmap maps background, just our layer(s).

**Comment by chuyentt** [comment]
Thank you for your suggestion! The geojson_vi package mainly focuses on providing utilities for parsing, searching, and manipulating GeoJSON data. However, rendering support could be a beneficial feature.

Incorporating rendering capabilities directly into geojson_vi would require a significant update, and it's important to consider whether this would be the best approach. It could lead to the package becoming too generalized and less efficient at its core purpose - handling GeoJSON data.

However, creating a separate package (like geojson_vi_render) for rendering GeoJSON data in Flutter could be a viable alternative. This way, we could maintain the simplicity and efficiency of geojson_vi while offering an additional tool for those who need it. This approach would encourage modularity and better adherence to the single responsibility principle.

Would love to hear your thoughts on this.
